import { act, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { SLOT_ADMIN_USER_ID } from '../lib/admin'
import { advanceTournament, makeTournament, makeTournamentScore, publishTournament, registerForTournament, saveTournamentGuest, startTournament, startTournamentRound } from '../lib/domain'
import type { Tournament, TournamentInput, TournamentScore } from '../lib/tournamentTypes'
import { TournamentsPage } from './TournamentsPage'

vi.mock('../lib/repository', async () => {
  const { localTournamentRepository } = await import('../lib/tournamentRepository')
  return { repository: localTournamentRepository() }
})
const now = Date.UTC(2026, 9, 1, 10)
const admin = { id: SLOT_ADMIN_USER_ID, displayName: 'Jury', email: 'jury@example.test', createdAt: 1 }
const members = Array.from({ length: 8 }, (_, i) => ({ id: `p${i}`, displayName: `Giocatore ${i}`, email: `p${i}@example.test`, createdAt: 1 }))
const input: TournamentInput = { title: 'Torneo dei fagiani', startsAt: now + 7_200_000, venueId: 'sport-city-mantova', format: 'americano', pairing: 'rotating', capacity: 8, courts: 2, rounds: 3, pointsPerMatch: 24, scoreAccess: 'players' }
function fixture(overrides: Partial<TournamentInput> = {}, count = 4) {
  let t = publishTournament(makeTournament('qa', { ...input, ...overrides }, admin.id, now - 86_400_000), admin.id, now - 86_400_000)
  for (const u of members.slice(0, count)) t = registerForTournament(t, u, null, now - 86_400_000)
  return t
}
function seed(t: Tournament, scores: TournamentScore[] = []) {
  localStorage.setItem('bandeja-tournaments-v1', JSON.stringify({ tournaments: [t], scores: { [t.id]: scores } }))
  window.history.replaceState(null, '', `/#tornei/${t.id}`)
}
const show = (user = admin) => render(<TournamentsPage user={user} members={[admin, ...members]} onBack={vi.fn()} />)
async function typeCapacity(u: ReturnType<typeof userEvent.setup>, modal: HTMLElement, count: number) {
  const field = within(modal).getByRole('spinbutton', { name: 'Massimo partecipanti' })
  await u.clear(field)
  await u.type(field, String(count))
}

describe('TournamentsPage', () => {
  beforeEach(() => {
    localStorage.removeItem('bandeja-tournaments-v1')
    window.history.replaceState(null, '', '/#tornei')
    vi.spyOn(Date, 'now').mockReturnValue(now)
  })
  afterEach(() => vi.restoreAllMocks())
  it('plans timed tournaments from capacity, courts and total duration without a fixed preset', async () => {
    const u = userEvent.setup(); show()
    await u.click(screen.getByRole('button', { name: /Crea torneo/ }))
    const modal = screen.getByRole('dialog')
    await u.click(within(modal).getByRole('radio', { name: /Girone all’italiana/ }))
    await u.selectOptions(within(modal).getByLabelText('Durata delle partite'), 'timed')
    await typeCapacity(u, modal, 10)
    await u.clear(within(modal).getByLabelText('Campi disponibili'))
    await u.type(within(modal).getByLabelText('Campi disponibili'), '2')
    expect(within(modal).getByLabelText('Massimo partecipanti')).toHaveValue(10)
    expect(within(modal).getByLabelText('Campi disponibili')).toHaveValue(2)
    expect(within(modal).getByLabelText('Durata delle partite')).toHaveValue('timed')
    expect(within(modal).getByLabelText('Durata totale disponibile (minuti)')).toHaveValue(90)
    expect(within(modal).getByText('88 minuti')).toBeInTheDocument()
    await typeCapacity(u, modal, 12)
    expect(within(modal).getByText('8 minuti')).toBeInTheDocument()
    expect(within(modal).getByText('83 minuti')).toBeInTheDocument()
    await u.clear(within(modal).getByLabelText('Campi disponibili'))
    await u.type(within(modal).getByLabelText('Campi disponibili'), '1')
    expect(within(modal).getByRole('alert')).toHaveTextContent('108 minuti')
  })
  it('updates published logistics before cutoff, without losing registrations', async () => {
    seed(fixture({ format: 'round-robin', pairing: 'random-fixed', scoringMode: 'timed', totalMinutes: 90 }, 8))
    const u = userEvent.setup(); show()
    await u.click(screen.getByRole('button', { name: 'Modifica torneo' }))
    const modal = screen.getByRole('dialog')
    await typeCapacity(u, modal, 12)
    expect(within(modal).getByText('8 minuti')).toBeInTheDocument()
    await u.click(within(modal).getByRole('button', { name: 'Salva modifiche' }))
    expect(await screen.findByText('8/12')).toBeInTheDocument()
    expect(screen.getByText('27 minuti')).toBeInTheDocument()
    expect(screen.getByText(/Stima aggiornata sugli iscritti attuali/)).toBeInTheDocument()
  })
  it('blocks an odd attendance draw but allows admin corrections after cutoff', () => {
    seed(fixture({ startsAt: now, format: 'round-robin', pairing: 'random-fixed', scoringMode: 'timed', totalMinutes: 90 }, 7))
    show()
    expect(screen.getByRole('button', { name: 'Modifica torneo' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Sorteggia e prepara tabellone' })).toBeDisabled()
    expect(screen.getByText(/Il numero è dispari/)).toBeInTheDocument()
  })
  it('lets the organizer add, rename and remove external entrants', async () => {
    seed(fixture()); const u = userEvent.setup(); show()
    await u.click(screen.getByRole('button', { name: /Aggiungi ospite/ }))
    await u.type(screen.getByLabelText('Nome dell’ospite'), 'Ciccio')
    await u.click(screen.getByRole('button', { name: 'Salva ospite' }))
    await u.click(await screen.findByRole('button', { name: 'Gestisci ospite Ciccio' }))
    await u.clear(screen.getByLabelText('Nome dell’ospite'))
    await u.type(screen.getByLabelText('Nome dell’ospite'), 'Ciccio Rossi')
    await u.click(screen.getByRole('button', { name: 'Salva ospite' }))
    await u.click(await screen.findByRole('button', { name: 'Gestisci ospite Ciccio Rossi' }))
    await u.click(screen.getByRole('button', { name: 'Rimuovi ospite' }))
    await u.click(screen.getByRole('button', { name: 'Conferma rimozione ospite' }))
    expect(screen.queryByText(/Ciccio Rossi · Ospite/)).not.toBeInTheDocument()
  })
  it.each(['open', 'running', 'completed', 'cancelled'] as const)('keeps guest names editable on a %s tournament after cutoff', async status => {
    const enrolled = saveTournamentGuest(fixture({ startsAt: now }, 3), 'guest:ciccio', 'Ciccio', null, admin.id, now - 86_400_000)
    const drawn = status === 'running' || status === 'completed' ? startTournament(enrolled, admin.id, 42, now) : enrolled
    const tournament = { ...drawn, status }
    seed(tournament)
    const u = userEvent.setup(); show()
    if (tournament.currentRound > 0) await u.click(screen.getByRole('button', { name: 'Dettagli' }))
    expect(screen.queryByRole('button', { name: /Aggiungi ospite/ })).not.toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Modifica nome ospite Ciccio' }))
    const modal = screen.getByRole('dialog')
    expect(within(modal).queryByRole('button', { name: 'Rimuovi ospite' })).not.toBeInTheDocument()
    await u.clear(within(modal).getByLabelText('Nome dell’ospite'))
    await u.type(within(modal).getByLabelText('Nome dell’ospite'), 'Ciccio Rossi')
    await u.click(within(modal).getByRole('button', { name: 'Salva nome' }))
    expect(await screen.findByRole('button', { name: 'Modifica nome ospite Ciccio Rossi' })).toBeInTheDocument()
    const saved = JSON.parse(localStorage.getItem('bandeja-tournaments-v1')!).tournaments[0] as Tournament
    expect(saved.registrations['guest:ciccio'].displayName).toBe('Ciccio Rossi')
    expect(saved.registrations['guest:ciccio'].joinedAt).toBe(tournament.registrations['guest:ciccio'].joinedAt)
    expect(saved.matches).toEqual(tournament.matches)
  })
  it('keeps guest management hidden from other members', () => {
    seed(fixture()); show(members[7])
    expect(screen.queryByRole('button', { name: /Aggiungi ospite/ })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Modifica torneo' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Prova in privato' })).not.toBeInTheDocument()
  })
  it('copies a real tournament configuration to rehearsal without changing its local source', async () => {
    const t = fixture({ format: 'mexicano', capacity: 12, courts: 3 }, 8)
    seed(t); const original = localStorage.getItem('bandeja-tournaments-v1')
    const u = userEvent.setup(); show()
    await u.click(screen.getByRole('button', { name: 'Prova in privato' }))
    await u.click(screen.getByRole('button', { name: 'Prepara simulazione privata' }))
    expect(await screen.findByText('12/12')).toBeInTheDocument()
    expect(screen.getByRole('region', { name: 'Strumenti della simulazione' })).toBeInTheDocument()
    expect(localStorage.getItem('bandeja-tournaments-v1')).toBe(original)
  })
  it('lets a creator edit published details while protecting existing entries and rules', async () => {
    const t = { ...fixture({}, 5), createdBy: members[0].id }
    seed(t); const u = userEvent.setup(); show(members[0])
    await u.click(screen.getByRole('button', { name: 'Modifica torneo' }))
    const modal = screen.getByRole('dialog')
    expect(within(modal).getByLabelText('Massimo partecipanti')).toHaveAttribute('min', '5')
    expect(within(modal).getAllByRole('radio').every(r => r.closest('fieldset')?.disabled)).toBe(true)
    await u.clear(within(modal).getByLabelText('Nome del torneo'))
    await u.type(within(modal).getByLabelText('Nome del torneo'), 'Coppa aggiornata')
    fireEvent.change(within(modal).getByLabelText('Data'), { target: { value: '2026-10-02' } })
    await u.selectOptions(within(modal).getByLabelText('Circolo'), 'tennis-club-mantova')
    await typeCapacity(u, modal, 12)
    await u.click(within(modal).getByRole('button', { name: 'Salva modifiche' }))
    expect(await screen.findByRole('heading', { name: 'Coppa aggiornata' })).toBeInTheDocument()
    expect(screen.getByText('5/12')).toBeInTheDocument()
    const saved = JSON.parse(localStorage.getItem('bandeja-tournaments-v1')!).tournaments[0]
    expect(saved.registrations).toEqual(t.registrations)
    expect(saved.createdBy).toBe(members[0].id)
    expect(saved.startsAt).toBe(t.startsAt + 86_400_000)
  })
  it('lets admin edit another creator’s closed undrawn tournament without moving its date', async () => {
    const t = { ...fixture({ startsAt: now }, 4), createdBy: members[0].id }
    seed(t); const u = userEvent.setup(); show()
    await u.click(screen.getByRole('button', { name: 'Modifica torneo' }))
    const modal = screen.getByRole('dialog')
    expect(within(modal).getByText(/altro membro come amministratore/)).toBeInTheDocument()
    await typeCapacity(u, modal, 12)
    await u.click(within(modal).getByRole('button', { name: 'Salva modifiche' }))
    expect(await screen.findByText('4/12')).toBeInTheDocument()
    const saved = JSON.parse(localStorage.getItem('bandeja-tournaments-v1')!).tournaments[0]
    expect(saved.startsAt).toBe(t.startsAt)
    expect(saved.registrations).toEqual(t.registrations)
  })
  it('only offers metadata to admin after drawing and preserves saved results', async () => {
    const t = { ...startTournament(fixture({ startsAt: now }, 4), admin.id, 42, now), createdBy: members[0].id }
    const scores = [makeTournamentScore(t, 'r1-m1', 14, 10, admin.id, undefined, 0, now)]
    seed(t, scores); const u = userEvent.setup(); show()
    await u.click(screen.getByRole('button', { name: 'Dettagli' }))
    await u.click(screen.getByRole('button', { name: 'Modifica torneo' }))
    const modal = screen.getByRole('dialog')
    expect(within(modal).queryByLabelText('Massimo partecipanti')).not.toBeInTheDocument()
    expect(within(modal).queryByLabelText('Durata delle partite')).not.toBeInTheDocument()
    expect(within(modal).getByText(/Calendario, coppie e risultati restano invariati/)).toBeInTheDocument()
    await u.clear(within(modal).getByLabelText('Nome del torneo'))
    await u.type(within(modal).getByLabelText('Nome del torneo'), 'Torneo corretto')
    await u.click(within(modal).getByRole('button', { name: 'Salva modifiche' }))
    expect(await screen.findByRole('heading', { name: 'Torneo corretto' })).toBeInTheDocument()
    const saved = JSON.parse(localStorage.getItem('bandeja-tournaments-v1')!)
    expect(saved.tournaments[0].matches).toEqual(t.matches)
    expect(saved.scores.qa).toEqual(scores)
  })
  it('does not offer edits to a creator after drawing', () => {
    seed({ ...startTournament(fixture({ startsAt: now }, 4), admin.id, 42, now), createdBy: members[0].id })
    show(members[0])
    expect(screen.queryByRole('button', { name: 'Modifica torneo' })).not.toBeInTheDocument()
  })
  it.each([0, 6])('can switch a long timed tournament back to standard with %i entrants', async count => {
    const t = fixture({ format: 'round-robin', pairing: 'random-fixed', capacity: 6, scoringMode: 'timed', totalMinutes: 180 }, count)
    seed(t)
    const u = userEvent.setup(); show()
    await u.click(screen.getByRole('button', { name: 'Modifica torneo' }))
    const modal = screen.getByRole('dialog')
    await u.selectOptions(within(modal).getByLabelText('Durata delle partite'), 'standard')
    await u.click(within(modal).getByRole('button', { name: 'Salva modifiche' }))
    expect(await screen.findByText('Torneo modificato. Iscrizioni e risultati conservati.')).toBeInTheDocument()
    const saved = JSON.parse(localStorage.getItem('bandeja-tournaments-v1')!).tournaments[0]
    expect(saved).toMatchObject({ scoringMode: 'standard', totalMinutes: null, matchMinutes: 15 })
    expect(saved.registrations).toEqual(t.registrations)
  })
  it('lets the creator change match duration with entrants while preserving fixed pairs', async () => {
    let t = { ...fixture({ format: 'round-robin', pairing: 'chosen-fixed' }, 8), createdBy: members[0].id }
    t = registerForTournament(t, members[0], members[1].id, now)
    t = registerForTournament(t, members[1], members[0].id, now)
    seed(t); const u = userEvent.setup(); show(members[0])
    await u.click(screen.getByRole('button', { name: 'Modifica torneo' }))
    const modal = screen.getByRole('dialog')
    expect(within(modal).getByLabelText('Coppie fisse')).toBeDisabled()
    expect(within(modal).getByLabelText('Durata delle partite')).toBeEnabled()
    await u.selectOptions(within(modal).getByLabelText('Durata delle partite'), 'timed')
    await typeCapacity(u, modal, 12)
    await u.click(within(modal).getByRole('button', { name: 'Salva modifiche' }))
    expect(await screen.findByText('Torneo modificato. Iscrizioni e risultati conservati.')).toBeInTheDocument()
    const saved = JSON.parse(localStorage.getItem('bandeja-tournaments-v1')!).tournaments[0]
    expect(saved).toMatchObject({ scoringMode: 'timed', capacity: 12, totalMinutes: 90, matchMinutes: 8 })
    expect(saved.registrations).toEqual(t.registrations)
  })
  it('handles empty, huge and incompatible typed capacities without building an invalid schedule', async () => {
    seed(fixture({ format: 'round-robin', pairing: 'random-fixed', scoringMode: 'timed', totalMinutes: 90 }, 8))
    const u = userEvent.setup(); show()
    await u.click(screen.getByRole('button', { name: 'Modifica torneo' }))
    const modal = screen.getByRole('dialog'), field = within(modal).getByLabelText('Massimo partecipanti')
    await u.clear(field)
    expect(field).toHaveValue(null)
    expect(field).toBeInvalid()
    await typeCapacity(u, modal, 999999)
    expect(field).toBeInvalid()
    expect(within(modal).getByRole('alert')).toHaveTextContent('numero pari')
    await typeCapacity(u, modal, 7)
    expect(field).toBeInvalid()
    await typeCapacity(u, modal, 9)
    await u.click(within(modal).getByRole('button', { name: 'Salva modifiche' }))
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    expect(JSON.parse(localStorage.getItem('bandeja-tournaments-v1')!).tournaments[0].capacity).toBe(8)
  })
  it('starts the shared timer before enabling game scores and accepts a draw', async () => {
    const t = startTournament(fixture({ startsAt: now, format: 'round-robin', pairing: 'random-fixed', scoringMode: 'timed', capacity: 8 }, 8), admin.id, 42, now)
    seed(t); const u = userEvent.setup(); show()
    expect(screen.getByRole('timer')).toHaveTextContent('15:00')
    expect(screen.queryByRole('button', { name: /Inserisci risultato/ })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Conferma turno e prosegui' })).toBeDisabled()
    await u.click(screen.getByRole('button', { name: 'Avvia timer del turno' }))
    await u.click((await screen.findAllByRole('button', { name: /Inserisci risultato/ }))[0])
    const modal = screen.getByRole('dialog'), fields = within(modal).getAllByRole('spinbutton')
    await u.type(fields[0], '4'); await u.type(fields[1], '4')
    await u.click(within(modal).getByRole('button', { name: 'Salva risultato' }))
    expect(await screen.findByRole('button', { name: /Modifica risultato/ })).toBeInTheDocument()
    expect(screen.getByText('Classifica coppie · V–N–P: vinte, pareggiate, perse')).toBeInTheDocument()
  })
  it('reconstructs an expired timer and never advances the round automatically', () => {
    const t = startTournamentRound(startTournament(fixture({ startsAt: now - 900_000, format: 'round-robin', pairing: 'random-fixed', scoringMode: 'timed' }, 8), admin.id, 42, now - 900_000), admin.id, now - 900_000)
    seed(t); show()
    expect(screen.getByRole('timer')).toHaveTextContent('00:00')
    expect(screen.getByText(/Tempo scaduto:/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Conferma turno e prosegui' })).toBeDisabled()
    expect(screen.getByText('Mancano 2 risultati per confermare il turno.')).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Turno 1 di 3' })).toBeInTheDocument()
  })
  it('groups play controls, confirms an early stop, keeps scores editable and advances only when complete', async () => {
    const t = startTournamentRound(startTournament(fixture({ startsAt: now, format: 'round-robin', pairing: 'random-fixed', scoringMode: 'timed' }, 8), admin.id, 42, now), admin.id, now - 60_000)
    seed(t); const u = userEvent.setup(); const page = show()
    const live = screen.getByRole('region', { name: 'Turno corrente' })
    expect(within(live).getByRole('timer')).toHaveTextContent('14:00')
    expect(within(live).getAllByRole('button', { name: /Inserisci risultato/ })).toHaveLength(2)
    expect(screen.queryByRole('heading', { name: 'Iscritti' })).not.toBeInTheDocument()
    await u.click(within(live).getByRole('button', { name: 'Concludi turno' }))
    await u.click(within(screen.getByRole('dialog')).getByRole('button', { name: /Chiudi/ }))
    expect(JSON.parse(localStorage.getItem('bandeja-tournaments-v1')!).tournaments[0].roundEndedAt).toBeNull()
    await u.click(within(live).getByRole('button', { name: 'Concludi turno' }))
    await u.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Conferma' }))
    expect(screen.getByRole('button', { name: 'Conferma turno e prosegui' })).toBeDisabled()
    page.unmount(); show()
    expect(screen.getByRole('timer')).toHaveAccessibleName('Tempo rimasto alla chiusura')
    expect(screen.queryByRole('button', { name: 'Avvia timer del turno' })).not.toBeInTheDocument()
    for (let i = 0; i < 2; i++) {
      await u.click(screen.getAllByRole('button', { name: /Inserisci risultato/ })[0])
      const fields = within(screen.getByRole('dialog')).getAllByRole('spinbutton')
      await u.type(fields[0], '3'); await u.type(fields[1], '2')
      await u.click(screen.getByRole('button', { name: 'Salva risultato' }))
    }
    await u.click(screen.getByRole('button', { name: 'Classifica' }))
    expect(screen.getByRole('heading', { name: 'Classifica provvisoria' })).toBeInTheDocument()
    expect(screen.queryByRole('timer')).not.toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Turno in corso' }))
    await u.click(screen.getByRole('button', { name: 'Conferma turno e prosegui' }))
    await u.click(screen.getByRole('button', { name: 'Conferma' }))
    expect(screen.getByRole('heading', { name: 'Turno 2 di 3' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Avvia timer del turno' })).toBeEnabled()
    expect(screen.getByRole('timer')).toHaveTextContent('15:00')
  })
  it('never gives an ordinary player control of the shared timer or round advancement', () => {
    const t = startTournamentRound(startTournament(fixture({ startsAt: now, format: 'round-robin', pairing: 'random-fixed', scoringMode: 'timed' }, 8), admin.id, 42, now), admin.id, now)
    seed(t); show(members[0])
    expect(screen.queryByRole('button', { name: 'Concludi turno' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Conferma turno e prosegui' })).not.toBeInTheDocument()
    expect(screen.getAllByRole('button', { name: /Inserisci risultato/ })).toHaveLength(1)
  })
  it('offers early stop next to completed scores without going back to the timer', () => {
    const t = startTournamentRound(startTournament(fixture({ startsAt: now, format: 'round-robin', pairing: 'random-fixed', scoringMode: 'timed' }, 8), admin.id, 42, now), admin.id, now)
    const scores = Object.values(t.matches).filter(m => m.round === 1).map(m => makeTournamentScore(t, m.id, 3, 2, admin.id, undefined, 0, now))
    seed(t, scores); show()
    expect(screen.getByRole('button', { name: 'Concludi turno in anticipo' })).toBeEnabled()
    expect(screen.queryByRole('button', { name: 'Conferma turno e prosegui' })).not.toBeInTheDocument()
  })
  it.each([admin, members[0]])('$displayName chooses a formula and privately saves then publishes their tournament', async creator => {
    const u = userEvent.setup(); show(creator)
    await u.click(screen.getByRole('button', { name: /Crea torneo/ }))
    const modal = screen.getByRole('dialog')
    expect(within(modal).getAllByRole('radio')).toHaveLength(4)
    await u.type(within(modal).getByLabelText('Nome del torneo'), 'Coppa del gruppo')
    await u.click(within(modal).getByRole('radio', { name: /Girone all’italiana/ }))
    await u.selectOptions(within(modal).getByLabelText('Coppie fisse'), 'chosen-fixed')
    await u.selectOptions(within(modal).getByLabelText('Circolo'), 'tennis-club-mantova')
    expect(within(modal).getByLabelText('Chi può inserire i risultati')).toHaveValue('players')
    await u.click(within(modal).getByRole('button', { name: 'Salva bozza privata' }))
    expect(await screen.findByRole('heading', { name: 'Coppa del gruppo' })).toBeInTheDocument()
    expect(screen.getByText('Bozza privata')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Iscriviti al torneo' })).not.toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Pubblica al gruppo' }))
    await u.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Conferma' }))
    expect(await screen.findByRole('button', { name: 'Iscriviti al torneo' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Modifica torneo' })).toBeInTheDocument()
  })
  it('members see the creation button but never see other members’ private drafts', () => {
    localStorage.setItem('bandeja-tournaments-v1', JSON.stringify({ tournaments: [makeTournament('secret', input, admin.id, now)], scores: {} }))
    show(members[0])
    expect(screen.getByRole('button', { name: /Crea torneo/ })).toBeInTheDocument()
    expect(screen.queryByText(input.title)).not.toBeInTheDocument()
    expect(screen.getByText('Il primo torneo aspetta voi')).toBeInTheDocument()
  })
  it('a member sees their own drafts and published tournaments without leaking other drafts', () => {
    const own = makeTournament('mine', { ...input, title: 'La mia coppa' }, members[0].id, now)
    const secret = makeTournament('secret', { ...input, title: 'Coppa segreta' }, members[1].id, now)
    localStorage.setItem('bandeja-tournaments-v1', JSON.stringify({ tournaments: [own, secret, fixture()], scores: {} }))
    show(members[0])
    expect(screen.getByRole('heading', { name: 'La mia coppa' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: input.title })).toBeInTheDocument()
    expect(screen.queryByText('Coppa segreta')).not.toBeInTheDocument()
  })
  it('a non-playing creator can score every match and advance in organizer-only mode', async () => {
    const t = { ...startTournament(fixture({ startsAt: now, scoreAccess: 'admin' }, 4), admin.id, 42, now), createdBy: members[7].id }
    seed(t); const u = userEvent.setup(); show(members[7])
    await u.click(await screen.findByRole('button', { name: /Inserisci risultato/ }))
    const modal = screen.getByRole('dialog'), fields = within(modal).getAllByRole('spinbutton')
    await u.type(fields[0], '14'); await u.type(fields[1], '10')
    await u.click(within(modal).getByRole('button', { name: 'Salva risultato' }))
    await u.click(await screen.findByRole('button', { name: 'Conferma turno e prosegui' }))
    await u.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Conferma' }))
    expect(await screen.findByRole('heading', { name: 'Turno 2 di 3' })).toBeInTheDocument()
  })
  it('members join, choose a partner and withdraw without writing for anyone else', async () => {
    seed(fixture({ format: 'round-robin', pairing: 'chosen-fixed' }, 2))
    const u = userEvent.setup(); show(members[2])
    await u.click(await screen.findByRole('button', { name: 'Iscriviti al torneo' }))
    await u.selectOptions(screen.getByRole('combobox', { name: /Scegli il tuo compagno/ }), 'p0')
    expect(await screen.findByText('In attesa di Giocatore 0')).toBeInTheDocument()
    expect(screen.queryByText(/Coppia confermata con/)).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Sorteggia/ })).not.toBeInTheDocument()
    await u.click(screen.getByRole('button', { name: 'Ritira iscrizione' }))
    expect(await screen.findByRole('button', { name: 'Iscriviti al torneo' })).toBeInTheDocument()
    expect(screen.getByText('2/8')).toBeInTheDocument()
  })
  it('closes registration on the exact cutoff, including a page left open across it', async () => {
    vi.useFakeTimers({ toFake: ['setInterval', 'clearInterval'] })
    seed(fixture({ startsAt: now + 3_600_001 }))
    show(members[7])
    expect(screen.getByRole('button', { name: 'Iscriviti al torneo' })).toBeInTheDocument()
    vi.spyOn(Date, 'now').mockReturnValue(now + 1)
    await act(async () => { vi.advanceTimersByTime(1000) })
    expect(screen.queryByRole('button', { name: 'Iscriviti al torneo' })).not.toBeInTheDocument()
    expect(screen.getByText('Iscrizioni chiuse')).toBeInTheDocument()
    vi.useRealTimers()
  })
  it('a player can save/correct only their own current match and sees validation errors', async () => {
    const t = startTournament(fixture({ startsAt: now }, 8), admin.id, 42, now)
    seed(t); const u = userEvent.setup(); show(members[0])
    const buttons = await screen.findAllByRole('button', { name: /Inserisci risultato/ })
    expect(buttons).toHaveLength(1)
    await u.click(buttons[0])
    const modal = screen.getByRole('dialog'), fields = within(modal).getAllByRole('spinbutton')
    await u.type(fields[0], '14'); await u.type(fields[1], '9')
    await u.click(within(modal).getByRole('button', { name: 'Salva risultato' }))
    expect(await within(modal).findByRole('alert')).toHaveTextContent(/sommare 24/)
    await u.clear(fields[1]); await u.type(fields[1], '10')
    await u.click(within(modal).getByRole('button', { name: 'Salva risultato' }))
    expect(await screen.findByRole('button', { name: /Modifica risultato/ })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Conferma turno/ })).not.toBeInTheDocument()
  })
  it('spectators can read results but have no scoring controls', async () => {
    const t = startTournament(fixture({ startsAt: now }, 4), admin.id, 42, now)
    seed(t); show(members[7])
    expect(await screen.findByText('Classifica provvisoria')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /risultato/ })).not.toBeInTheDocument()
  })
  it('admin confirms the completed bronze/final and a podium appears without altering old results', async () => {
    let t = startTournament(fixture({ startsAt: now, format: 'knockout', pairing: 'random-fixed' }, 8), admin.id, 42, now)
    let scores = Object.values(t.matches).map(m => makeTournamentScore(t, m.id, 6, 3, admin.id, undefined, 0, now))
    t = advanceTournament(t, scores, admin.id, now)
    scores = [...scores, ...Object.values(t.matches).filter(m => m.round === 2).map(m => makeTournamentScore(t, m.id, 6, 4, admin.id, undefined, 0, now))]
    seed(t, scores); const u = userEvent.setup(); show()
    await u.click(await screen.findByRole('button', { name: 'Concludi torneo e assegna il podio' }))
    await u.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Conferma' }))
    expect(await screen.findByRole('heading', { name: 'Il podio e la classifica finale' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Modifica risultato/ })).not.toBeInTheDocument()
    expect(screen.getByText('Concluso')).toBeInTheDocument()
  })
})
